import { jobStatus } from '@/+core/enums/jobStatus.enum';
import { HRAccount, Job } from '@/+core/utilities/types/admin.type';
import { hRAccountStatus as AccountStatus } from '@/+core/enums/hRAccountStatus.enum';

export const mockJobData: Job[] = [
  {
    id: '1',
    companyName: 'ABC Company',
    title: 'Software Engineer',
    level: 'Senior',
    salary: '$100,000 - $120,000',
    techs: ['JavaScript', 'React', 'Node.js'],
    experienceYearsMin: '5',
    experienceYearsMax: '8',
    typeContract: 'Full-time',
    type: 'Permanent',
    jobDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    interviewProcess: ['Phone interview', 'Technical test', 'On-site interview'],
    submittedDate: new Date('2024-04-01'),
    startDate: new Date('2024-05-01'),
    endDate: new Date('2024-08-01'),
    status: jobStatus.Approved,
  },
  {
    id: '2',
    companyName: 'XYZ Corporation',
    title: 'Data Scientist',
    level: 'Mid',
    salary: '$90,000 - $110,000',
    techs: ['Python', 'Machine Learning', 'SQL'],
    experienceYearsMin: '3',
    experienceYearsMax: '5',
    typeContract: 'Contract',
    type: 'Temporary',
    jobDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    interviewProcess: 'To be determined',
    submittedDate: new Date('2024-03-25'),
    startDate: new Date('2024-04-15'),
    endDate: new Date('2024-09-15'),
    status: jobStatus.Pending,
  },
  {
    id: '3',
    companyName: 'Example Corp',
    title: 'Product Manager',
    level: 'Mid',
    salary: '$80,000 - $100,000',
    techs: ['Product Management', 'Market Analysis', 'Communication'],
    experienceYearsMin: '4',
    experienceYearsMax: '6',
    typeContract: 'Full-time',
    type: 'Permanent',
    jobDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    interviewProcess: ['Phone interview', 'In-person interview', 'Presentation'],
    submittedDate: new Date('2024-04-10'),
    startDate: new Date('2024-05-15'),
    endDate: new Date('2024-08-15'),
    status: jobStatus.Approved,
  },
  {
    id: '4',
    companyName: 'Tech Solutions Inc.',
    title: 'Frontend Developer',
    level: 'Junior',
    salary: '$60,000 - $80,000',
    techs: ['HTML', 'CSS', 'JavaScript', 'React'],
    experienceYearsMin: '1',
    experienceYearsMax: '3',
    typeContract: 'Full-time',
    type: 'Permanent',
    jobDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    interviewProcess: ['Technical test', 'On-site interview'],
    submittedDate: new Date('2024-04-05'),
    startDate: new Date('2024-05-10'),
    endDate: new Date('2024-08-10'),
    status: jobStatus.Approved,
  },
  {
    id: '5',
    companyName: 'Data Insights Co.',
    title: 'Data Analyst',
    level: 'Entry',
    salary: '$50,000 - $70,000',
    techs: ['SQL', 'Data Visualization', 'Statistical Analysis'],
    experienceYearsMin: '0',
    experienceYearsMax: '2',
    typeContract: 'Full-time',
    type: 'Permanent',
    jobDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    interviewProcess: 'To be determined',
    submittedDate: new Date('2024-04-08'),
    startDate: new Date('2024-05-20'),
    endDate: new Date('2024-08-20'),
    status: jobStatus.Approved,
  },
  {
    id: '6',
    companyName: 'Innovative Tech Ltd.',
    title: 'Software Developer',
    level: 'Mid',
    salary: '$80,000 - $100,000',
    techs: ['Java', 'Spring', 'Hibernate'],
    experienceYearsMin: '3',
    experienceYearsMax: '5',
    typeContract: 'Contract',
    type: 'Temporary',
    jobDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    interviewProcess: ['Phone interview', 'Coding test', 'On-site interview'],
    submittedDate: new Date('2024-04-03'),
    startDate: new Date('2024-05-05'),
    endDate: new Date('2024-08-05'),
    status: jobStatus.Approved,
  },
  {
    id: '7',
    companyName: 'ABC Corporation',
    title: 'Marketing Manager',
    level: 'Senior',
    salary: '$90,000 - $110,000',
    techs: ['Marketing Strategy', 'Brand Management', 'Market Research'],
    experienceYearsMin: '5',
    experienceYearsMax: '8',
    typeContract: 'Full-time',
    type: 'Permanent',
    jobDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    interviewProcess: ['Phone interview', 'In-person interview', 'Presentation'],
    submittedDate: new Date('2024-04-02'),
    startDate: new Date('2024-05-01'),
    endDate: new Date('2024-08-01'),
    status: jobStatus.Pending,
  },
  {
    id: '8',
    companyName: 'Tech Innovations Co.',
    title: 'Backend Developer',
    level: 'Mid',
    salary: '$80,000 - $100,000',
    techs: ['Python', 'Django', 'MySQL'],
    experienceYearsMin: '3',
    experienceYearsMax: '5',
    typeContract: 'Full-time',
    type: 'Permanent',
    jobDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    interviewProcess: ['Phone interview', 'Technical test', 'On-site interview'],
    submittedDate: new Date('2024-03-28'),
    startDate: new Date('2024-05-03'),
    endDate: new Date('2024-08-03'),
    status: jobStatus.Pending,
  },
  {
    id: '9',
    companyName: 'DataTech Solutions',
    title: 'Data Engineer',
    level: 'Mid',
    salary: '$90,000 - $110,000',
    techs: ['Big Data', 'Hadoop', 'Spark'],
    experienceYearsMin: '4',
    experienceYearsMax: '6',
    typeContract: 'Contract',
    type: 'Temporary',
    jobDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    interviewProcess: ['Phone interview', 'Coding test', 'On-site interview'],
    submittedDate: new Date('2024-04-06'),
    startDate: new Date('2024-05-08'),
    endDate: new Date('2024-08-08'),
    status: jobStatus.Approved,
  },
  {
    id: '10',
    companyName: 'XYZ Solutions',
    title: 'QA Engineer',
    level: 'Junior',
    salary: '$60,000 - $80,000',
    techs: ['Manual Testing', 'Automated Testing', 'Bug Tracking'],
    experienceYearsMin: '1',
    experienceYearsMax: '3',
    typeContract: 'Contract',
    type: 'Temporary',
    jobDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    interviewProcess: 'To be determined',
    submittedDate: new Date('2024-04-04'),
    startDate: new Date('2024-05-06'),
    endDate: new Date('2024-08-06'),
    status: jobStatus.Approved,
  },
];

export const mockHRAccountData: HRAccount[] = [
  {
    id: '1',
    companyName: 'Apple Inc.',
    taxCode: 123456789,
    displayName: 'Apple',
    fields: ['Product Development', 'Marketing', 'Sales'],
    address: '1 Apple Park Way, Cupertino, CA',
    status: AccountStatus.Pending,
  },
  {
    id: '2',
    companyName: 'Microsoft Corporation',
    taxCode: 987654321,
    displayName: 'Microsoft',
    fields: ['Software Development', 'Cloud Computing', 'Gaming'],
    address: 'One Microsoft Way, Redmond, WA',
    status: AccountStatus.Approved,
  },
  {
    id: '3',
    companyName: 'Amazon.com, Inc.',
    taxCode: 2468101214,
    displayName: 'Amazon',
    fields: ['E-commerce', 'Cloud Services', 'Digital Streaming'],
    address: '410 Terry Ave N, Seattle, WA',
    status: AccountStatus.Rejected,
  },
  {
    id: '4',
    companyName: 'Tesla, Inc.',
    taxCode: 1357924680,
    displayName: 'Tesla',
    fields: ['Electric Vehicles', 'Energy Storage', 'Solar Energy'],
    address: '3500 Deer Creek Road, Palo Alto, CA',
    status: AccountStatus.Rejected,
  },
  {
    id: '5',
    companyName: 'Google LLC',
    taxCode: 246813579,
    displayName: 'Google',
    fields: ['Search Engine', 'Online Advertising', 'Cloud Computing'],
    address: '1600 Amphitheatre Parkway, Mountain View, CA',
    status: AccountStatus.Approved,
  },
  {
    id: '6',
    companyName: 'Facebook, Inc.',
    taxCode: 135792468,
    displayName: 'Facebook',
    fields: ['Social Networking', 'Digital Advertising', 'Virtual Reality'],
    address: '1 Hacker Way, Menlo Park, CA',
    status: AccountStatus.Approved,
  },
  {
    id: '7',
    companyName: 'Walmart Inc.',
    taxCode: 975318642,
    displayName: 'Walmart',
    fields: ['Retail', 'E-commerce', 'Grocery'],
    address: '702 SW 8th St, Bentonville, AR',
    status: AccountStatus.Approved,
  },
  {
    id: '8',
    companyName: 'Toyota Motor Corporation',
    taxCode: 864209753,
    displayName: 'Toyota',
    fields: ['Automobile Manufacturing', 'Hybrid Vehicles', 'Autonomous Driving'],
    address: '1 Toyota-cho, Toyota City, Aichi Prefecture, Japan',
    status: AccountStatus.Rejected,
  },
  {
    id: '9',
    companyName: 'Samsung Electronics Co., Ltd.',
    taxCode: 579318642,
    displayName: 'Samsung',
    fields: ['Consumer Electronics', 'Semiconductors', 'Telecommunications'],
    address: '129 Samsung-ro, Maetan-dong, Yeongtong-gu, Suwon-si, Gyeonggi-do, South Korea',
    status: AccountStatus.Pending,
  },
  {
    id: '10',
    companyName: 'Intel Corporation',
    taxCode: 426093871,
    displayName: 'Intel',
    fields: ['Semiconductors', 'Processors', 'Data Centers'],
    address: '2200 Mission College Blvd, Santa Clara, CA',
    status: AccountStatus.Approved,
  },
  {
    id: '11',
    companyName: 'Sony Corporation',
    taxCode: 793642018,
    displayName: 'Sony',
    fields: ['Consumer Electronics', 'Entertainment', 'Gaming'],
    address: '1-7-1 Konan, Minato-ku, Tokyo, Japan',
    status: AccountStatus.Pending,
  },
  {
    id: '12',
    companyName: 'Nike, Inc.',
    taxCode: 103857294,
    displayName: 'Nike',
    fields: ['Athletic Footwear', 'Apparel', 'Sports Equipment'],
    address: '1 Bowerman Dr, Beaverton, OR',
    status: AccountStatus.Approved,
  },
];
